package com.wl.wlp2ploansystem.publicsubsystem.repositories;

import com.wl.wlp2ploansystem.publicsubsystem.entities.BaseRepository;
import com.wl.wlp2ploansystem.publicsubsystem.entities.Base_AttachmentCategoryClassification;

public interface Base_AttachmentCategoryClassificationRepository extends BaseRepository<Base_AttachmentCategoryClassification> {
}
